import Header from "../components/Header";
import Head from "next/head";
import ProjectPage from "../components/ProjectPage";
export default function Projects({ props }) {
  return (
    <div>
      <Head>
        <title>Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <ProjectPage />
    </div>
  );
}
